Data:
  dt: 0.1
  grid_size: 64
  seed: 1234
  crop: "crop"
  field: "vorticity"
  norm: true
  shuffle: true
  size: 100

Model:
  h_dim: 32
  z_dim: 32
  in_channels: 4
  time_embed_dim: 128
  hidden_dim: 256
  n_layers: 3
  ae_path: "runs/006/epoch_10_0.9957_1.1559.pth"
  lfm_path: "runs/006/epoch_10_0.9957_1.1559.pth"

Training:
  method: "std"
  epochs: 1000
  batch_size: 5
  learning_rate: 1e-3
  divergence_loss_weight: 1e-3
  gamma: 0.98
  last_lr: 1e-4
  sigma_min: 0.01

device: "cpu"