Data:
  grid_size: 128
  norm: true
  size: 500

Model:
  channel_size: 3  
  channel_size_out: 3  
  partition_size: [1, 1, 1]  
  drop_class_labels: True  
  save_path: "runs/004/epoch_1000_0.0207_0.0264.pth" # std

Training:
  method: "std"
  epochs: 1000
  batch_size: 4
  learning_rate: 5e-4
  divergence_loss_weight: 1e-3
  sigma_min: 0.0
  gamma: 0.995
  last_lr: 1e-5

device: "cuda:2"