Data:
  grid_size: 32
  norm: true
  size: 500

Model:
  channel_size: 16  
  channel_size_out: 16 
  partition_size: [1, 1, 1]  
  drop_class_labels: True  
  save_path: "runs/013/epoch_2000_1.8676_1.8525.pth" # std VAE 12
  #save_path: "runs/015/epoch_2000_2.4147_2.3946.pth" # std AE 12

Training:
  method: "std"
  epochs: 2000
  batch_size: 5
  learning_rate: 5e-4
  divergence_loss_weight: 1e-1
  sigma_min: 0.0
  gamma: 0.995
  last_lr: 1e-5

device: "cuda:0"