Data:
  grid_size: 128
  norm: true
  size: 500

Model:
  channel_size: 3  
  channel_size_out: 3  
  partition_size: [1, 1, 1] 
  drop_class_labels: True  
  save_path: "runs/002/epoch_800_0.0427_0.0408.pth" # std

Training:
  method: "std"
  epochs: 1000
  batch_size: 4
  learning_rate: 5e-4
  ddpm_loss_weight: 1e-3
  gamma: 0.995
  last_lr: 1e-5

Diffusion:
  beta_schedule: linear
  num_diffusion_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  mask_schedule_sig: 3

device: "cuda:3"