Data:
  dt: 0.1
  grid_size: 128
  seed: 1234
  crop: "crop"
  field: "vorticity"
  norm: true
  shuffle: true
  size: 100

Model:
  h_dim: 32
  z_dim: 1028
  in_channels: 4
  out_ch: 4                  # Added — number of output channels
  ch: 16                   # Added — base channel size
  ch_mult: [1, 2, 4, 8, 16]      # Added — multiplier for channels at each resolution
  num_res_blocks: 2          # Added — number of residual blocks per resolution
  dropout: 0.1               # Already present
  resamp_with_conv: true     # Added — if True, use conv for down/up-sampling
  latent_dim: 1024
  time_embed_dim: 128
  hidden_dim: 256
  n_layers: 3
  ae_path: "runs/006/epoch_10_0.9957_1.1559.pth"
  lfm_path: "runs/006/epoch_10_0.9957_1.1559.pth"

Training:
  method: "std"
  epochs: 1000
  batch_size: 1
  learning_rate: 1e-3
  divergence_loss_weight: 1e-3
  gamma: 0.98
  last_lr: 1e-4
  sigma_min: 0.01

device: "cuda:0"