Data:
  grid_size: 32
  norm: true
  size: 500

Model:
  channel_size: 16  
  channel_size_out: 16 
  partition_size: [1, 1, 1]  
  drop_class_labels: True  
  save_path: "runs/122/epoch_20_1.4402_1.4486.pth" # std

Training:
  method: "std"
  epochs: 1000
  batch_size: 4
  learning_rate: 5e-4
  divergence_loss_weight: 1e-1
  sigma_min: 0.0
  gamma: 0.995
  last_lr: 1e-5

device: "cuda:2"