Data:
  dt: 0.1
  grid_size: 128
  seed: 1234
  crop: "crop"
  field: "vorticity"
  norm: true
  shuffle: true
  size: 500

Model:
  channel_size: 3  # Number of input channels
  channel_size_out: 3  # Number of output channels
  partition_size: [1, 1, 1]  # Partition size for region partitioning
  drop_class_labels: True  # Whether to drop class labels
  save_path: "runs/127/epoch_90_0.0672_0.0397.pth"

Training:
  method: "std"
  epochs: 1000
  batch_size: 4
  learning_rate: 1e-4
  ddpm_loss_weight: 1e-3
  gamma: 0.98
  last_lr: 1e-5

Diffusion:
  beta_schedule: linear
  num_diffusion_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  mask_schedule_sig: 3

device: "cpu"