Data:
  dt: 0.1
  grid_size: 128
  seed: 1234
  crop: "crop"
  field: "vorticity"
  norm: true
  shuffle: true
  size: 100

Model:
  ch: 32
  out_ch: 4
  ch_mult: [1, 2]
  num_res_blocks: 1
  attn_resolutions: []
  dropout: 0.1
  in_channels: 4
  resamp_with_conv: true
  save_path: "runs/013/epoch_240_0.2047_0.1725.pth"

Training:
  method: "std"
  epochs: 1000
  batch_size: 2
  learning_rate: 1e-4
  divergence_loss_weight: 1e-3
  sigma_min: 0.01
  gamma: 0.98
  last_lr: 1e-5

device: "cuda:3"