Data:
  dt: 0.1
  grid_size: 64
  seed: 1234
  crop: "crop"
  field: "vorticity"
  norm: true
  shuffle: true
  size: 100

Model:
  ch: 32
  out_ch: 4
  ch_mult: [1, 2]
  num_res_blocks: 1
  attn_resolutions: []
  dropout: 0.1
  in_channels: 4
  resamp_with_conv: true
  save_path: "runs/024/epoch_50_0.0014_0.0386.pth"

Training:
  method: "std"
  epochs: 1000
  batch_size: 1
  learning_rate: 1e-4
  ddpm_loss_weight: 1e-3
  gamma: 0.98
  last_lr: 1e-5

Diffusion:
  beta_schedule: linear
  num_diffusion_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  mask_schedule_sig: 3

device: "cpu"