Data:
  dt: 0.1
  grid_size: 128
  seed: 1234
  crop: "crop"
  field: "vorticity"
  norm: true
  shuffle: true
  size: 100

Model:
  channel_size: 3  # Number of input channels
  channel_size_out: 3  # Number of output channels
  partition_size: [2, 2, 2]  # Partition size for region partitioning
  drop_class_labels: True  # Whether to drop class labels
  #save_path: "runs/013/epoch_240_0.2047_0.1725.pth"
  #save_path: "runs/077/epoch_60_0.2951_0.2749.pth"
  save_path: "runs/079/epoch_210_0.3281_0.3193.pth"

Training:
  method: "std"
  epochs: 1000
  batch_size: 5
  learning_rate: 1e-4
  divergence_loss_weight: 1e-1
  sigma_min: 0.01
  gamma: 0.98
  last_lr: 1e-5

device: "cuda:2"