Data:
  dt: 0.1
  grid_size: 64
  seed: 1234
  crop: "crop"
  field: "vorticity"
  norm: true
  shuffle: true
  size: 10

Model:
  h_dim: 128
  z_dim: 64
  in_channels: 3
  save_path: "runs/006/epoch_10_0.9957_1.1559.pth"

Training:
  method: "std"
  epochs: 10
  batch_size: 1
  learning_rate: 1e-4
  divergence_loss_weight: 1e-3

device: "cuda"