Data:
  grid_size: 128
  norm: true
  size: 500

Model:
  channel_size: 3 
  channel_size_out: 3  
  partition_size: [1, 1, 1]  
  drop_class_labels: True  
  save_path: "runs/001/epoch_1000_0.2174_0.2236.pth" # std, sigma 0
  #save_path: "runs/005/epoch_1000_0.2170_0.2325.pth" # std, sigma 0.01
  #save_path: "runs/006/epoch_1000_0.2077_0.2025.pth" # std, sigma 0.001


Training:
  method: "PINN_dyn"
  epochs: 1000
  batch_size: 4
  effective_batch_size: 8
  learning_rate: 5e-4
  divergence_loss_weight: 1e-1
  sigma_min: 0.001
  gamma: 0.995
  last_lr: 1e-5

device: "cuda:2"