Data:
  grid_size: 128
  norm: true
  size: 500

Model:
  in_channels: 3
  hidden_size: 256
  depth: 2
  num_res_block: 2
  res_size: 32
  z_dim: 16
  ae_path: "runs/007/epoch_1000_18.9396_19.2390.pth" # VAE 12
  #ae_path: "runs/011/epoch_1000_18.6367_18.9378.pth" # AE 12
  #ae_path: "runs/017/epoch_1000_4.8884_4.9092.pth" # VAE 3
  #ae_path: "runs/016/epoch_1000_3.8754_3.8646.pth" # AE 3 
  
Training:
  epochs: 1000
  batch_size: 5
  learning_rate: 1e-3
  gamma: 0.995
  last_lr: 1e-5

device: "cuda:3"